name: Upload APK to Appwrite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Appwrite CLI
        run: npm install -g appwrite-cli

      - name: Add Appwrite to PATH
        run: echo "$(npm root -g)/.bin" >> $GITHUB_PATH

      - name: Set Appwrite Project
        run: |
          appwrite client --endpoint "${{ secrets.APPWRITE_ENDPOINT }}" \
                          --project-id "${{ secrets.APPWRITE_PROJECT_ID }}" \
                          --key "${{ secrets.APPWRITE_API_KEY }}"



      - name: Upload APK to Appwrite
        run: appwrite storage create-file --bucket-id "Testapk" --file-id "testapk" --file "test.apk"
