name: Upload APK to Appwrite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify APK file
        run: |
          ls -lh test.apk
          file test.apk
          md5sum test.apk

      - name: Upload APK to Appwrite
        run: |
          curl -X POST "https://cloud.appwrite.io/v1/storage/buckets/Testapk/files" \
            -H "Content-Type: multipart/form-data" \
            -H "X-Appwrite-Project: ${{ secrets.APPWRITE_PROJECT_ID }}" \
            -H "X-Appwrite-Key: ${{ secrets.APPWRITE_API_KEY }}" \
            -F "file=@test.apk" \
            -F "fileId=testapk-$(date +%s)"
