name: Upload test.apk to Appwrite

on:
  push:
    branches:
      - main  # 또는 원하는 브랜치

jobs:
  upload-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Appwrite CLI
        run: |
          curl -sL https://appwrite.io/cli/install.sh | bash
          appwrite login --key ${{ secrets.APPWRITE_API_KEY }}

      - name: Upload test.apk to Appwrite
        run: |
          appwrite storage createFile \
            --bucketId ${{ secrets.APPWRITE_BUCKET_ID }} \
            --fileId test-apk \
            --file ./test.apk
