name: Upload APK to Appwrite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Appwrite CLI
        run: npm install -g appwrite-cli

      - name: Add Appwrite to PATH
        run: echo "$(npm root -g)/.bin" >> $GITHUB_PATH

      - name: Set up Appwrite Environment Variables
        run: |
          echo "APPWRITE_ENDPOINT=https://cloud.appwrite.io/v1" >> $GITHUB_ENV
          echo "APPWRITE_PROJECT=${{ secrets.APPWRITE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "APPWRITE_KEY=${{ secrets.APPWRITE_API_KEY }}" >> $GITHUB_ENV
          echo "APPWRITE_SELF_SIGNED=true" >> $GITHUB_ENV  # 필요한 경우 추가

      - name: Upload APK to Appwrite
        env:
          APPWRITE_PROJECT: ${{ secrets.APPWRITE_PROJECT_ID }}
          APPWRITE_KEY: ${{ secrets.APPWRITE_API_KEY }}
          APPWRITE_ENDPOINT: "https://cloud.appwrite.io/v1"
        run: appwrite storage create-file --bucket-id "Testapk" --file-id "testapk" --file "test.apk"
