name: Upload APK to Appwrite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Appwrite CLI
        run: npm install -g appwrite

      - name: Add Appwrite to PATH
        run: echo "$(npm root -g)/.bin" >> $GITHUB_PATH

      - name: Set up Appwrite CLI authentication
        run: appwrite client --endpoint "https://cloud.appwrite.io/v1" --project "${{ secrets.APPWRITE_PROJECT_ID }}" --key "${{ secrets.APPWRITE_API_KEY }}"

      - name: Upload APK to Appwrite
        run: appwrite storage createFile --bucketId "Testapk" --fileId "testapk" --file "test.apk"
